In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/name-that-llm/sample_submission.parquet
/kaggle/input/competitions/name-that-llm/train.csv
/kaggle/input/competitions/name-that-llm/test.csv

### Idea + Thought Process
1. check how many prompts each 18 models(6 families) have
2. length of prompt for each model (make a box plot) length vs model
3. words each model likes to use
4. punctuation (- , : ; ) usage by model
5. pattern
6. i think ill also have to think about family characteristics then to model characteristics

In [6]:
# lets see how the sample submission looks like
# we can use -> import pyarrow

# but i know pandas so ill use it
sample = '/kaggle/input/competitions/name-that-llm/sample_submission.parquet'
train = '/kaggle/input/competitions/name-that-llm/train.csv'
test = '/kaggle/input/competitions/name-that-llm/test.csv'

import pandas as pd

df = pd.read_parquet(sample)
df.head()

             id    model
0  00353fb1c541  gpt-5.5
1  005f5a9a6139  gpt-5.5
2  0062a53d5487  gpt-5.5

In [9]:
# lets see the training data
df = pd.read_csv(train)
df.head()

,id,prompt_id,text,model
0,0018b3765972,p081,"When a language dies, a particular astronomy d...",qwen3.8-max
1,0041ac86ee93,p073,Data science communities matter because they a...,claude-sonnet-5
2,005a19083eae,p120,"In the final twilight of time, the last embers...",gemini-3.6-flash
3,009319596f10,p073,Data science communities matter because they t...,gpt-5.6-terra
4,00d3e8c92596,p097,"Deep inside each ear, three tiny loops of bone...",glm-5.3-flash